version: '3.8'

services:
  db:
    hostname: dumptruck-db
    build: .
    image: dumptruck-postgres-age
    container_name: dumptruck-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dumptruck
      POSTGRES_PASSWORD: dumptruck
      POSTGRES_DB: dumptruck
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
