name: Build

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dumptruck
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: dumptruck
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: dumptruck.exe
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a dumptruck-windows.zip dumptruck.exe
          move dumptruck-windows.zip ..\..\..

      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd target/${{ matrix.target }}/release
          zip -r dumptruck-linux.zip dumptruck
          mv dumptruck-linux.zip ../../../

      - name: Package macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd target/${{ matrix.target }}/release
          zip -r dumptruck-macos.zip dumptruck
          mv dumptruck-macos.zip ../../../
